#!/bin/bash

DN=${1:-0}
NB=${2:-1024}

mkdir -p /mnt/$3/afhba.$DN
echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.0.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
outroot=/mnt/$3/afhba.$DN/$(cat /dev/rtm-t.0.ctrl/acq_ident)
mkdir -p $outroot
echo stream to $outroot
CONCAT=3999 NBUFS=$NB RTM_DEVNUM=$DN OUTROOT=$outroot ./STREAM/rtm-t-stream-disk

